### ISSUE TITLE
Strange encoding: utf-8 instead windows-1251

### ISSUE THREAD

**Issue by Bargamut** [Azq2/perl-html5-dom#5]
Hi! )

Thanks for this library!
But we have a bug. (?)
We need to work with windows-1251. Not UTF-8.
But every time it returns result with utf-8 charset.

I have simple example:

**index.pl (windows-1251)**

```
use HTML5::DOM;

my $textWin1251 = "<p>Если заголовок заполнен, а подзаголовка нет – для материала все остается так же, как раньше.</p>";
my $parser = HTML5::DOM->new();

print $DOM_tree->encoding; # WINDOWS-1251
print $DOM_tree->utf8; # 0

my $DOM_tree = $parser->parse($text);
my $nodes = $DOM_tree->querySelectorAll('body > *');
my $div2 = $DOM_tree->createElement('div');

$div2->innerHTML(qq{<div>Вставляемый фрагмент кода</div>});

$nodes->[0]->after($div2);

$textWin1251 = $DOM_tree->body->innerHTML;

print $textWin1251;
```

**Return**

`<p>Р•СЃР»Рё Р·Р°РіРѕР»РѕРІРѕРє Р·Р°РїРѕР»РЅРµРЅ, Р° РїРѕРґР·Р°РіРѕР»РѕРІРєР° РЅРµС‚ вЂ“ РґР»СЏ РјР°С‚РµСЂРёР°Р»Р° РІСЃРµ РѕСЃС‚Р°РµС‚СЃСЏ С‚Р°Рє Р¶Рµ, РєР°Рє СЂР°РЅСЊС€Рµ.</p><div>Вставляемый фрагмент кода</div>`

Options like
```
my $parser = HTML5::DOM->new({
  encoding => "WINDOWS-1251", # and / or
  utf8 => 0, # and / or
  default_encoding => "WINDOWS-1251"
});
```
and each other has no affect.

**Comment by Azq2** [comment]
Hm, github not showing me this issue. 
Original lib https://github.com/lexborisov/myhtml work only with UTF-8

> Support encodings for output
> Program working in UTF-8 and returns all in UTF-8

Simple logic:
1. If **encoding** != UTF-8 => lib recoding anything to UTF-8
2. If **encoding** == "UTF-8" => don't touch original bytes, because lib expects perl code in UTF-8.

But you use windows-1521 in code. Unexpected, but has workaround. 
In case **2** UTF-8 really means raw bytes. If force set encoding to "UTF-8" myhtml lib fine works with **any** ASCII compatible encodings. 

In this case internal encoding recoder not involved, only true bytes. 
In future, i add "raw"/ENCODING_RAW encoding for this case (working with raw bytes) and will add documentation. 
But now you can use this hack. Example:
```use warnings;
use strict;
use HTML5::DOM;
use Encode;

my $cp1251_input_string = "<p>Если заголовок заполнен, а подзаголовка нет – для материала все остается так же, как раньше.</p><a></a>\n";

my $tree = HTML5::DOM->new({
	encoding	=> "UTF-8" # UTF-8 really means work with raw bytes
})->parse($cp1251_input_string);

my $cp1251_input_string2 = "<div>Вставляемый фрагмент кода</div>\n";

$tree->at('a')->innerHTML($cp1251_input_string2);

print $tree;
```

**Comment by Bargamut** [comment]
Hi, @Azq2 !
Thanks for answer!

I'll try this hack.
Now I use `encode(decode())` to switch the source encoding before and after processing.

**Comment by Azq2** [comment]
Okay. But my way more efficient and simplier. Please, write if it works. :)

**Comment by Bargamut** [comment]
@Azq2 sure! )
I'll try it in project on the weekend. Can you keep this issue open for 2-3 days?

**Comment by Azq2** [comment]
You still alive? :)

**Comment by Bargamut** [comment]
Oh my!
Sorry, my fault!

For our purposes we use this:
```perl
my $text = "кириллический текст статьи";
my $parser = HTML5::DOM->new();
my $DOM_tree = $parser->parse($text, {
		encoding => "windows-1251",
		encoding_use_bom => 0
});
my $textNodes = $DOM_tree->querySelectorAll('body > p');
my $importText = encode('utf8', decode('cp1251', 'кириллица'));

# any code...

$intextWrapper->innerHTML($importText);
$textNodes->[$index]->after($intextWrapper);

$t = $DOM_tree->body->innerHTML;
$t = encode('cp1251', decode('utf8', $t));

# a little bit of more hell..
```

Thank you for your answer! Sorry again! I think issue is resolved.
